name: SSM Params to Github
author: Sam Anthony

runs:
  using: "composite"
  steps:
  - name: Import SSM Params
    shell: bash
    run: |
      ls -la
      cd scripts
      composer install
      php run.php $GITHUB_OUTPUT
