name: SSM Params to Github
author: Sam Anthony

# TODO-SAM since the dotevn file is never needed outside of this action, I dont think it is senesible to pass the dotenv-path anymore
inputs:
  GITHUB_TOKEN:
    description: Pass in the GITHUB_TOKEN
    required: true
  dotenv-path:
    required: true

runs:
  using: "composite"
  steps:

  - name: PHP Composer for github-action-php-composer-cached
    uses: the-pistol/github-action-php-composer-cached@alternative-implementation
    with:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      composer-working-dir: ${{ github.action_path }}/scripts
      dev-option: "exclude-dev"

  - name: Dump SSM Params into temp dotenv file
    shell: bash
    run: |
      cd ${{ github.action_path }}/scripts
      echo "dotenv-path:"
      echo ${{ inputs.dotenv-path }}
      mkdir -p ${{ inputs.dotenv-path }}
      php run.php > ${{ inputs.dotenv-path }}/.env

  - name: Load dotenv file
    uses: xom9ikk/dotenv@v2
    with:
      path: ${{ inputs.dotenv-path }}

