name: SSM Params to Github
author: Sam Anthony

inputs:
#  env-name:
#    required: true
  dontenv-file-path:
    required: true

runs:
  using: "composite"
  steps:
  - name: Import SSM Params
    shell: bash
    run: |
      ls -la
      cd ${{ github.action_path }}/scripts
      composer install
      php run.php > ${{ dontenv-file-path }}
