name: SSM Params to Github
author: Sam Anthony

inputs:
  GITHUB_TOKEN:
    description: Pass in the GITHUB_TOKEN
    required: true

runs:
  using: "composite"
  steps:

  - name: PHP Composer for github-action-php-composer-cached
    # TODO-SAM use master github branch here
    uses: the-pistol/github-action-php-composer-cached@alternative-implementation
    with:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      composer-working-dir: ${{ github.action_path }}/scripts
      dev-option: "exclude-dev"

  - name: Dump SSM Params into temp dotenv file
    id: dotenv
    shell: bash
    run: |
      cd ${{ github.action_path }}/scripts
      DOTENV_FOLDER="${{ runner.temp }}/$RANDOM"
      echo "DOTENV_FOLDER:"
      echo $DOTENV_FOLDER
      echo "$DOTENV_FOLDER/.env"
      mkdir -p $DOTENV_FOLDER
      echo "folder=$DOTENV_FOLDER" >> "$GITHUB_OUTPUT"
      php run.php > "$DOTENV_FOLDER/.env"
      cat "$DOTENV_FOLDER/.env"

  - name: Load dotenv file
    uses: xom9ikk/dotenv@v2
    with:
      path: ${{ steps.dotenv.outputs.folder }}

