name: SSM Params to Github
author: Sam Anthony

inputs:
#  env-name:
#    required: true
  dotenv-path:
    required: true

runs:
  using: "composite"
  steps:

  - name: PHP Composer for github-action-php-composer-cached
    uses: the-pistol/github-action-php-composer-cached@master
    with:
      composer-working-dir: ./scripts

  - name: Dump SSM Params into temp dotenv file
    shell: bash
    run: |
      cd ${{ github.action_path }}/scripts
      echo "dotenv-path:"
      echo ${{ inputs.dotenv-path }}
      mkdir -p ${{ inputs.dotenv-path }}
      php run.php > ${{ inputs.dotenv-path }}/.env

  - name: Load dotenv file
    uses: xom9ikk/dotenv@v2
    with:
      path: ${{ inputs.dotenv-path }}

