name: SSM Params to Github
author: Sam Anthony

inputs:
#  env-name:
#    required: true
  dotenv-file-path:
    required: true

runs:
  using: "composite"
  steps:
  - name: Import SSM Params
    shell: bash
    # TODO-SAM composer caching?
    run: |
      cd ${{ github.action_path }}/scripts
      composer install
      echo "dotenv-file-path:"
      echo ${{ inputs.dotenv-file-path }}
      echo "Generated Dotenv contents:"
      php run.php | tee ${{ inputs.dotenv-file-path }}
